---
#- name: Copy main sudoers file 
#  copy:
#    src: sudoers
#    dest: /etc/sudoers
#    owner: root
#    group: root 
#    mode: '0440'

- name: check all existing sudoers files
  shell: ls -1 /etc/sudoers.d/
  register: sudoers_files
  changed_when: False

- name: Remove unmanaged sudoers files
  vars:
    unmanaged_files: "{{hostvars[inventory_hostname]['sudoers']['unmanaged_files']}}"
  file: path=/etc/sudoers.d/{{ item }} state=absent
  with_items: "{{sudoers_files.stdout_lines}}"
  when: "item not in hostvars[inventory_hostname]['sudoers']['groups'] and item not in hostvars[inventory_hostname]['sudoers']['users'] and item not in unmanaged_files"

- name: Configure group sudoers
  template: 
    src: sudoers.j2
    dest: /etc/sudoers.d/{{item}}
    owner: root
    group: root
    mode: '0644'
  with_items:
    "{{hostvars[inventory_hostname]['sudoers']['groups']}}"
  when: "hostvars[inventory_hostname]['sudoers']['groups'] is defined"

- name: Configure user specific sudoers
  template: 
    src: user_sudoers.j2
    dest: /etc/sudoers.d/{{item}}
    owner: root
    group: root
    mode: '0644'
  with_items:
    "{{hostvars[inventory_hostname]['sudoers']['users']}}"
  when: "hostvars[inventory_hostname]['sudoers']['users'] is defined"
